DROP DATABASE IF EXISTS simalytics;

DROP USER simalytics@localhost;

CREATE DATABASE simalytics;

USE simalytics;

-- Users
CREATE TABLE T_USER (
       ID INTEGER AUTO_INCREMENT,
       EMAIL_ADDRESS VARCHAR(100),
       FIRST_NAME VARCHAR(100),
       SURNAME VARCHAR(100),
       CREATED DATETIME,
       LAST_LOGIN DATETIME,
       TOS_ACCEPTANCE BOOLEAN,
       PASSWORD_HASH VARCHAR(100),
       SOURCE VARCHAR(100), -- Facebook/OpenID
       PRIMARY KEY (ID)
);

-- Profiles
CREATE TABLE T_PROFILE (
       ID INTEGER AUTO_INCREMENT,
       USER_ID INTEGER,
       TITLE VARCHAR(200), -- Drawn from site home page via HTTP request
       URL VARCHAR(100),
       PRIVATE_KEY BLOB, -- for session verification
       CREATED DATETIME,
       DELETED DATETIME,
       PRIMARY KEY (ID)
);

ALTER TABLE T_PROFILE ADD CONSTRAINT T_PROFILE_FK1 FOREIGN KEY (USER_ID) REFERENCES T_USER(ID);

-- Sessions
CREATE TABLE T_GUEST_SESSION (
       ID INTEGER AUTO_INCREMENT,
       START_TIME DATETIME,
       DURATION_MS LONG,
       PROFILE_ID INTEGER,
       SOURCE_IP VARCHAR(20),
       EXTERN_IDENT VARCHAR(100), -- hashed external identifier
       PRIMARY KEY (ID)
);

ALTER TABLE T_GUEST_SESSION ADD CONSTRAINT T_GUEST_SESSION_FK1 FOREIGN KEY (PROFILE_ID) REFERENCES T_PROFILE (ID);

-- PCUs
CREATE TABLE T_PCU (
       ID INTEGER AUTO_INCREMENT,
       PROFILE_ID INTEGER,
       PUBLIC_KEY BLOB, -- for session generation
       URL VARCHAR(255),
       PCU_IDENTIFIER VARCHAR(255), -- dependent on the client, may be a single identifier (forum thread ID, or multiple, e.g. "<thread-ID>;<post-ID>"
       CREATED DATETIME,
       MODIFIED DATETIME,
       PRIMARY KEY (ID)
);

-- PCU mapped back to user (creator) via T_PROFILE
ALTER TABLE T_PCU ADD CONSTRAINT T_PCU_FK1 FOREIGN KEY (PROFILE_ID) REFERENCES T_PROFILE (ID);

-- Interactions
CREATE TABLE T_PCU_INTERACTION (
       ID INTEGER AUTO_INCREMENT,
       PCU_ID INTEGER,
       INTERACTION_TIME DATETIME,
       INTERACTION VARCHAR(100), -- OVERLAY_OPENED, MORE_INFORMATION, CANCEL, PAY ... use enum?
       GUEST_SESSION_ID  INTEGER,
       PRIMARY KEY (ID)
);

ALTER TABLE T_PCU_INTERACTION ADD CONSTRAINT T_PCU_INTERACTION_FK1 FOREIGN KEY (PCU_ID) REFERENCES T_PCU (ID);
ALTER TABLE T_PCU_INTERACTION ADD CONSTRAINT T_PCU_INTERACTION_FK2 FOREIGN KEY (GUEST_SESSION_ID) REFERENCES T_GUEST_SESSION (ID);

-- Interaction data
CREATE TABLE T_PCU_INTERACTION_DATA (
       ID INTEGER AUTO_INCREMENT,
       PCU_INTERACTION_ID INTEGER,
       HTTP_HEADER_KEY VARCHAR(100),
       HTTP_HEADER_VAL LONGTEXT,
       PRIMARY KEY (ID)
);

ALTER TABLE T_PCU_INTERACTION_DATA ADD CONSTRAINT T_PCU_INTERACTION_DATA_FK1 FOREIGN KEY (PCU_INTERACTION_ID) REFERENCES T_PCU_INTERACTION (ID);

-- User(s)
GRANT SELECT,UPDATE,DELETE,INSERT ON simalytics.* TO simalytics@localhost IDENTIFIED BY 's1m@lytic3';